// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mBodies.proto

package com.moomoo.moonect.proto;

public interface MConnectReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MConnectReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serviceId = 1;</code>
   * @return The serviceId.
   */
  java.lang.String getServiceId();
  /**
   * <code>string serviceId = 1;</code>
   * @return The bytes for serviceId.
   */
  com.google.protobuf.ByteString
      getServiceIdBytes();
}
