// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mHeaders.proto

package com.moomoo.moonect.proto;

/**
 * Protobuf type {@code MHeader}
 */
public final class MHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MHeader)
    MHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MHeader.newBuilder() to construct.
  private MHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MHeader() {
    version_ = "";
    sender_ = "";
    messageId_ = "";
    messageName_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MHeader();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moomoo.moonect.proto.MHeaders.internal_static_MHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moomoo.moonect.proto.MHeaders.internal_static_MHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moomoo.moonect.proto.MHeader.class, com.moomoo.moonect.proto.MHeader.Builder.class);
  }

  /**
   * Protobuf enum {@code MHeader.MessageName}
   */
  public enum MessageName
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>M_CONNECT_REQ = 1;</code>
     */
    M_CONNECT_REQ(1),
    /**
     * <code>M_HEART_BEAT_REQ = 2;</code>
     */
    M_HEART_BEAT_REQ(2),
    /**
     * <code>M_SESSION_CREATE_REQ = 3;</code>
     */
    M_SESSION_CREATE_REQ(3),
    /**
     * <code>M_SESSION_DELETE_REQ = 4;</code>
     */
    M_SESSION_DELETE_REQ(4),
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>M_STATUS_NOTIFY = 5;</code>
     */
    M_STATUS_NOTIFY(5),
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>M_CONNECT_RES = 6;</code>
     */
    M_CONNECT_RES(6),
    /**
     * <code>M_HEART_BEAT_RES = 7;</code>
     */
    M_HEART_BEAT_RES(7),
    /**
     * <code>M_SESSION_CREATE_RES = 8;</code>
     */
    M_SESSION_CREATE_RES(8),
    /**
     * <code>M_SESSION_DELETE_RES = 9;</code>
     */
    M_SESSION_DELETE_RES(9),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>M_CONNECT_REQ = 1;</code>
     */
    public static final int M_CONNECT_REQ_VALUE = 1;
    /**
     * <code>M_HEART_BEAT_REQ = 2;</code>
     */
    public static final int M_HEART_BEAT_REQ_VALUE = 2;
    /**
     * <code>M_SESSION_CREATE_REQ = 3;</code>
     */
    public static final int M_SESSION_CREATE_REQ_VALUE = 3;
    /**
     * <code>M_SESSION_DELETE_REQ = 4;</code>
     */
    public static final int M_SESSION_DELETE_REQ_VALUE = 4;
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>M_STATUS_NOTIFY = 5;</code>
     */
    public static final int M_STATUS_NOTIFY_VALUE = 5;
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>M_CONNECT_RES = 6;</code>
     */
    public static final int M_CONNECT_RES_VALUE = 6;
    /**
     * <code>M_HEART_BEAT_RES = 7;</code>
     */
    public static final int M_HEART_BEAT_RES_VALUE = 7;
    /**
     * <code>M_SESSION_CREATE_RES = 8;</code>
     */
    public static final int M_SESSION_CREATE_RES_VALUE = 8;
    /**
     * <code>M_SESSION_DELETE_RES = 9;</code>
     */
    public static final int M_SESSION_DELETE_RES_VALUE = 9;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageName valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageName forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return M_CONNECT_REQ;
        case 2: return M_HEART_BEAT_REQ;
        case 3: return M_SESSION_CREATE_REQ;
        case 4: return M_SESSION_DELETE_REQ;
        case 5: return M_STATUS_NOTIFY;
        case 6: return M_CONNECT_RES;
        case 7: return M_HEART_BEAT_RES;
        case 8: return M_SESSION_CREATE_RES;
        case 9: return M_SESSION_DELETE_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageName>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageName> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageName>() {
            public MessageName findValueByNumber(int number) {
              return MessageName.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.moomoo.moonect.proto.MHeader.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageName[] VALUES = values();

    public static MessageName valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageName(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MHeader.MessageName)
  }

  public static final int VERSION_FIELD_NUMBER = 1;
  private volatile java.lang.Object version_;
  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_FIELD_NUMBER = 2;
  private volatile java.lang.Object sender_;
  /**
   * <code>string sender = 2;</code>
   * @return The sender.
   */
  @java.lang.Override
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sender_ = s;
      return s;
    }
  }
  /**
   * <code>string sender = 2;</code>
   * @return The bytes for sender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGEID_FIELD_NUMBER = 3;
  private volatile java.lang.Object messageId_;
  /**
   * <code>string messageId = 3;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <code>string messageId = 3;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGENAME_FIELD_NUMBER = 4;
  private int messageName_;
  /**
   * <code>.MHeader.MessageName messageName = 4;</code>
   * @return The enum numeric value on the wire for messageName.
   */
  @java.lang.Override public int getMessageNameValue() {
    return messageName_;
  }
  /**
   * <code>.MHeader.MessageName messageName = 4;</code>
   * @return The messageName.
   */
  @java.lang.Override public com.moomoo.moonect.proto.MHeader.MessageName getMessageName() {
    @SuppressWarnings("deprecation")
    com.moomoo.moonect.proto.MHeader.MessageName result = com.moomoo.moonect.proto.MHeader.MessageName.valueOf(messageName_);
    return result == null ? com.moomoo.moonect.proto.MHeader.MessageName.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timeStamp_;
  /**
   * <code>uint64 timeStamp = 5;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public long getTimeStamp() {
    return timeStamp_;
  }

  public static final int STATUSCODE_FIELD_NUMBER = 6;
  private int statusCode_;
  /**
   * <code>uint32 statusCode = 6;</code>
   * @return The statusCode.
   */
  @java.lang.Override
  public int getStatusCode() {
    return statusCode_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageId_);
    }
    if (messageName_ != com.moomoo.moonect.proto.MHeader.MessageName.NONE.getNumber()) {
      output.writeEnum(4, messageName_);
    }
    if (timeStamp_ != 0L) {
      output.writeUInt64(5, timeStamp_);
    }
    if (statusCode_ != 0) {
      output.writeUInt32(6, statusCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sender_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sender_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageId_);
    }
    if (messageName_ != com.moomoo.moonect.proto.MHeader.MessageName.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, messageName_);
    }
    if (timeStamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, timeStamp_);
    }
    if (statusCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(6, statusCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moomoo.moonect.proto.MHeader)) {
      return super.equals(obj);
    }
    com.moomoo.moonect.proto.MHeader other = (com.moomoo.moonect.proto.MHeader) obj;

    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getSender()
        .equals(other.getSender())) return false;
    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (messageName_ != other.messageName_) return false;
    if (getTimeStamp()
        != other.getTimeStamp()) return false;
    if (getStatusCode()
        != other.getStatusCode()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    hash = (37 * hash) + MESSAGENAME_FIELD_NUMBER;
    hash = (53 * hash) + messageName_;
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeStamp());
    hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
    hash = (53 * hash) + getStatusCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moomoo.moonect.proto.MHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.moomoo.moonect.proto.MHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moomoo.moonect.proto.MHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moomoo.moonect.proto.MHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MHeader)
      com.moomoo.moonect.proto.MHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moomoo.moonect.proto.MHeaders.internal_static_MHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moomoo.moonect.proto.MHeaders.internal_static_MHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moomoo.moonect.proto.MHeader.class, com.moomoo.moonect.proto.MHeader.Builder.class);
    }

    // Construct using com.moomoo.moonect.proto.MHeader.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      version_ = "";

      sender_ = "";

      messageId_ = "";

      messageName_ = 0;

      timeStamp_ = 0L;

      statusCode_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moomoo.moonect.proto.MHeaders.internal_static_MHeader_descriptor;
    }

    @java.lang.Override
    public com.moomoo.moonect.proto.MHeader getDefaultInstanceForType() {
      return com.moomoo.moonect.proto.MHeader.getDefaultInstance();
    }

    @java.lang.Override
    public com.moomoo.moonect.proto.MHeader build() {
      com.moomoo.moonect.proto.MHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moomoo.moonect.proto.MHeader buildPartial() {
      com.moomoo.moonect.proto.MHeader result = new com.moomoo.moonect.proto.MHeader(this);
      result.version_ = version_;
      result.sender_ = sender_;
      result.messageId_ = messageId_;
      result.messageName_ = messageName_;
      result.timeStamp_ = timeStamp_;
      result.statusCode_ = statusCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moomoo.moonect.proto.MHeader) {
        return mergeFrom((com.moomoo.moonect.proto.MHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moomoo.moonect.proto.MHeader other) {
      if (other == com.moomoo.moonect.proto.MHeader.getDefaultInstance()) return this;
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (!other.getSender().isEmpty()) {
        sender_ = other.sender_;
        onChanged();
      }
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        onChanged();
      }
      if (other.messageName_ != 0) {
        setMessageNameValue(other.getMessageNameValue());
      }
      if (other.getTimeStamp() != 0L) {
        setTimeStamp(other.getTimeStamp());
      }
      if (other.getStatusCode() != 0) {
        setStatusCode(other.getStatusCode());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              version_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              sender_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              messageId_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 32: {
              messageName_ = input.readEnum();

              break;
            } // case 32
            case 40: {
              timeStamp_ = input.readUInt64();

              break;
            } // case 40
            case 48: {
              statusCode_ = input.readUInt32();

              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string version = 1;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sender_ = "";
    /**
     * <code>string sender = 2;</code>
     * @return The sender.
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender = 2;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender = 2;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 2;</code>
     * @param value The bytes for sender to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sender_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object messageId_ = "";
    /**
     * <code>string messageId = 3;</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string messageId = 3;</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string messageId = 3;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string messageId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      
      messageId_ = getDefaultInstance().getMessageId();
      onChanged();
      return this;
    }
    /**
     * <code>string messageId = 3;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageId_ = value;
      onChanged();
      return this;
    }

    private int messageName_ = 0;
    /**
     * <code>.MHeader.MessageName messageName = 4;</code>
     * @return The enum numeric value on the wire for messageName.
     */
    @java.lang.Override public int getMessageNameValue() {
      return messageName_;
    }
    /**
     * <code>.MHeader.MessageName messageName = 4;</code>
     * @param value The enum numeric value on the wire for messageName to set.
     * @return This builder for chaining.
     */
    public Builder setMessageNameValue(int value) {
      
      messageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.MHeader.MessageName messageName = 4;</code>
     * @return The messageName.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MHeader.MessageName getMessageName() {
      @SuppressWarnings("deprecation")
      com.moomoo.moonect.proto.MHeader.MessageName result = com.moomoo.moonect.proto.MHeader.MessageName.valueOf(messageName_);
      return result == null ? com.moomoo.moonect.proto.MHeader.MessageName.UNRECOGNIZED : result;
    }
    /**
     * <code>.MHeader.MessageName messageName = 4;</code>
     * @param value The messageName to set.
     * @return This builder for chaining.
     */
    public Builder setMessageName(com.moomoo.moonect.proto.MHeader.MessageName value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageName_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.MHeader.MessageName messageName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageName() {
      
      messageName_ = 0;
      onChanged();
      return this;
    }

    private long timeStamp_ ;
    /**
     * <code>uint64 timeStamp = 5;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public long getTimeStamp() {
      return timeStamp_;
    }
    /**
     * <code>uint64 timeStamp = 5;</code>
     * @param value The timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStamp(long value) {
      
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timeStamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = 0L;
      onChanged();
      return this;
    }

    private int statusCode_ ;
    /**
     * <code>uint32 statusCode = 6;</code>
     * @return The statusCode.
     */
    @java.lang.Override
    public int getStatusCode() {
      return statusCode_;
    }
    /**
     * <code>uint32 statusCode = 6;</code>
     * @param value The statusCode to set.
     * @return This builder for chaining.
     */
    public Builder setStatusCode(int value) {
      
      statusCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 statusCode = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusCode() {
      
      statusCode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MHeader)
  }

  // @@protoc_insertion_point(class_scope:MHeader)
  private static final com.moomoo.moonect.proto.MHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moomoo.moonect.proto.MHeader();
  }

  public static com.moomoo.moonect.proto.MHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MHeader>
      PARSER = new com.google.protobuf.AbstractParser<MHeader>() {
    @java.lang.Override
    public MHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moomoo.moonect.proto.MHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

