// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mHeaders.proto

package com.moomoo.moonect.proto;

public interface MHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string version = 1;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string sender = 2;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 2;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string messageId = 3;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string messageId = 3;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>.MHeader.MessageName messageName = 4;</code>
   * @return The enum numeric value on the wire for messageName.
   */
  int getMessageNameValue();
  /**
   * <code>.MHeader.MessageName messageName = 4;</code>
   * @return The messageName.
   */
  com.moomoo.moonect.proto.MHeader.MessageName getMessageName();

  /**
   * <code>uint64 timeStamp = 5;</code>
   * @return The timeStamp.
   */
  long getTimeStamp();

  /**
   * <code>uint32 statusCode = 6;</code>
   * @return The statusCode.
   */
  int getStatusCode();
}
