// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mMessages.proto

package com.moomoo.moonect.proto;

/**
 * <pre>
 * 필드 번호 할당 시 범위 : 1 - 536,870,911
 * 19,000 - 19,999 는 예약되어 있어 사용 자제
 * 주로 1-15 사용 권장 (1byte 소모)
 * </pre>
 *
 * Protobuf type {@code MMessage}
 */
public final class MMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MMessage)
    MMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MMessage.newBuilder() to construct.
  private MMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moomoo.moonect.proto.MMessages.internal_static_MMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moomoo.moonect.proto.MMessages.internal_static_MMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moomoo.moonect.proto.MMessage.class, com.moomoo.moonect.proto.MMessage.Builder.class);
  }

  private int bodyCase_ = 0;
  private java.lang.Object body_;
  public enum BodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    MCONNECTREQ(2),
    MHEARTBEATREQ(3),
    MSESSIONCREATEREQ(4),
    MSESSIONDELETEREQ(5),
    MSTATUSNOTIFY(10),
    MCONNECTRES(12),
    MHEARTBEATRES(13),
    MSESSIONCREATERES(14),
    MSESSIONDELETERES(15),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 2: return MCONNECTREQ;
        case 3: return MHEARTBEATREQ;
        case 4: return MSESSIONCREATEREQ;
        case 5: return MSESSIONDELETEREQ;
        case 10: return MSTATUSNOTIFY;
        case 12: return MCONNECTRES;
        case 13: return MHEARTBEATRES;
        case 14: return MSESSIONCREATERES;
        case 15: return MSESSIONDELETERES;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  public static final int MHEADER_FIELD_NUMBER = 1;
  private com.moomoo.moonect.proto.MHeader mHeader_;
  /**
   * <code>.MHeader mHeader = 1;</code>
   * @return Whether the mHeader field is set.
   */
  @java.lang.Override
  public boolean hasMHeader() {
    return mHeader_ != null;
  }
  /**
   * <code>.MHeader mHeader = 1;</code>
   * @return The mHeader.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MHeader getMHeader() {
    return mHeader_ == null ? com.moomoo.moonect.proto.MHeader.getDefaultInstance() : mHeader_;
  }
  /**
   * <code>.MHeader mHeader = 1;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MHeaderOrBuilder getMHeaderOrBuilder() {
    return getMHeader();
  }

  public static final int MCONNECTREQ_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Requests
   * </pre>
   *
   * <code>.MConnectReq mConnectReq = 2;</code>
   * @return Whether the mConnectReq field is set.
   */
  @java.lang.Override
  public boolean hasMConnectReq() {
    return bodyCase_ == 2;
  }
  /**
   * <pre>
   * Requests
   * </pre>
   *
   * <code>.MConnectReq mConnectReq = 2;</code>
   * @return The mConnectReq.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MConnectReq getMConnectReq() {
    if (bodyCase_ == 2) {
       return (com.moomoo.moonect.proto.MConnectReq) body_;
    }
    return com.moomoo.moonect.proto.MConnectReq.getDefaultInstance();
  }
  /**
   * <pre>
   * Requests
   * </pre>
   *
   * <code>.MConnectReq mConnectReq = 2;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MConnectReqOrBuilder getMConnectReqOrBuilder() {
    if (bodyCase_ == 2) {
       return (com.moomoo.moonect.proto.MConnectReq) body_;
    }
    return com.moomoo.moonect.proto.MConnectReq.getDefaultInstance();
  }

  public static final int MHEARTBEATREQ_FIELD_NUMBER = 3;
  /**
   * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
   * @return Whether the mHeartBeatReq field is set.
   */
  @java.lang.Override
  public boolean hasMHeartBeatReq() {
    return bodyCase_ == 3;
  }
  /**
   * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
   * @return The mHeartBeatReq.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MHeartBeatReq getMHeartBeatReq() {
    if (bodyCase_ == 3) {
       return (com.moomoo.moonect.proto.MHeartBeatReq) body_;
    }
    return com.moomoo.moonect.proto.MHeartBeatReq.getDefaultInstance();
  }
  /**
   * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MHeartBeatReqOrBuilder getMHeartBeatReqOrBuilder() {
    if (bodyCase_ == 3) {
       return (com.moomoo.moonect.proto.MHeartBeatReq) body_;
    }
    return com.moomoo.moonect.proto.MHeartBeatReq.getDefaultInstance();
  }

  public static final int MSESSIONCREATEREQ_FIELD_NUMBER = 4;
  /**
   * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
   * @return Whether the mSessionCreateReq field is set.
   */
  @java.lang.Override
  public boolean hasMSessionCreateReq() {
    return bodyCase_ == 4;
  }
  /**
   * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
   * @return The mSessionCreateReq.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MSessionCreateReq getMSessionCreateReq() {
    if (bodyCase_ == 4) {
       return (com.moomoo.moonect.proto.MSessionCreateReq) body_;
    }
    return com.moomoo.moonect.proto.MSessionCreateReq.getDefaultInstance();
  }
  /**
   * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MSessionCreateReqOrBuilder getMSessionCreateReqOrBuilder() {
    if (bodyCase_ == 4) {
       return (com.moomoo.moonect.proto.MSessionCreateReq) body_;
    }
    return com.moomoo.moonect.proto.MSessionCreateReq.getDefaultInstance();
  }

  public static final int MSESSIONDELETEREQ_FIELD_NUMBER = 5;
  /**
   * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
   * @return Whether the mSessionDeleteReq field is set.
   */
  @java.lang.Override
  public boolean hasMSessionDeleteReq() {
    return bodyCase_ == 5;
  }
  /**
   * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
   * @return The mSessionDeleteReq.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MSessionDeleteReq getMSessionDeleteReq() {
    if (bodyCase_ == 5) {
       return (com.moomoo.moonect.proto.MSessionDeleteReq) body_;
    }
    return com.moomoo.moonect.proto.MSessionDeleteReq.getDefaultInstance();
  }
  /**
   * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MSessionDeleteReqOrBuilder getMSessionDeleteReqOrBuilder() {
    if (bodyCase_ == 5) {
       return (com.moomoo.moonect.proto.MSessionDeleteReq) body_;
    }
    return com.moomoo.moonect.proto.MSessionDeleteReq.getDefaultInstance();
  }

  public static final int MSTATUSNOTIFY_FIELD_NUMBER = 10;
  /**
   * <pre>
   * Notices
   * </pre>
   *
   * <code>.MStatusNotify mStatusNotify = 10;</code>
   * @return Whether the mStatusNotify field is set.
   */
  @java.lang.Override
  public boolean hasMStatusNotify() {
    return bodyCase_ == 10;
  }
  /**
   * <pre>
   * Notices
   * </pre>
   *
   * <code>.MStatusNotify mStatusNotify = 10;</code>
   * @return The mStatusNotify.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MStatusNotify getMStatusNotify() {
    if (bodyCase_ == 10) {
       return (com.moomoo.moonect.proto.MStatusNotify) body_;
    }
    return com.moomoo.moonect.proto.MStatusNotify.getDefaultInstance();
  }
  /**
   * <pre>
   * Notices
   * </pre>
   *
   * <code>.MStatusNotify mStatusNotify = 10;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MStatusNotifyOrBuilder getMStatusNotifyOrBuilder() {
    if (bodyCase_ == 10) {
       return (com.moomoo.moonect.proto.MStatusNotify) body_;
    }
    return com.moomoo.moonect.proto.MStatusNotify.getDefaultInstance();
  }

  public static final int MCONNECTRES_FIELD_NUMBER = 12;
  /**
   * <pre>
   * Responses
   * </pre>
   *
   * <code>.MConnectRes mConnectRes = 12;</code>
   * @return Whether the mConnectRes field is set.
   */
  @java.lang.Override
  public boolean hasMConnectRes() {
    return bodyCase_ == 12;
  }
  /**
   * <pre>
   * Responses
   * </pre>
   *
   * <code>.MConnectRes mConnectRes = 12;</code>
   * @return The mConnectRes.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MConnectRes getMConnectRes() {
    if (bodyCase_ == 12) {
       return (com.moomoo.moonect.proto.MConnectRes) body_;
    }
    return com.moomoo.moonect.proto.MConnectRes.getDefaultInstance();
  }
  /**
   * <pre>
   * Responses
   * </pre>
   *
   * <code>.MConnectRes mConnectRes = 12;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MConnectResOrBuilder getMConnectResOrBuilder() {
    if (bodyCase_ == 12) {
       return (com.moomoo.moonect.proto.MConnectRes) body_;
    }
    return com.moomoo.moonect.proto.MConnectRes.getDefaultInstance();
  }

  public static final int MHEARTBEATRES_FIELD_NUMBER = 13;
  /**
   * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
   * @return Whether the mHeartBeatRes field is set.
   */
  @java.lang.Override
  public boolean hasMHeartBeatRes() {
    return bodyCase_ == 13;
  }
  /**
   * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
   * @return The mHeartBeatRes.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MHeartBeatRes getMHeartBeatRes() {
    if (bodyCase_ == 13) {
       return (com.moomoo.moonect.proto.MHeartBeatRes) body_;
    }
    return com.moomoo.moonect.proto.MHeartBeatRes.getDefaultInstance();
  }
  /**
   * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MHeartBeatResOrBuilder getMHeartBeatResOrBuilder() {
    if (bodyCase_ == 13) {
       return (com.moomoo.moonect.proto.MHeartBeatRes) body_;
    }
    return com.moomoo.moonect.proto.MHeartBeatRes.getDefaultInstance();
  }

  public static final int MSESSIONCREATERES_FIELD_NUMBER = 14;
  /**
   * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
   * @return Whether the mSessionCreateRes field is set.
   */
  @java.lang.Override
  public boolean hasMSessionCreateRes() {
    return bodyCase_ == 14;
  }
  /**
   * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
   * @return The mSessionCreateRes.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MSessionCreateRes getMSessionCreateRes() {
    if (bodyCase_ == 14) {
       return (com.moomoo.moonect.proto.MSessionCreateRes) body_;
    }
    return com.moomoo.moonect.proto.MSessionCreateRes.getDefaultInstance();
  }
  /**
   * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MSessionCreateResOrBuilder getMSessionCreateResOrBuilder() {
    if (bodyCase_ == 14) {
       return (com.moomoo.moonect.proto.MSessionCreateRes) body_;
    }
    return com.moomoo.moonect.proto.MSessionCreateRes.getDefaultInstance();
  }

  public static final int MSESSIONDELETERES_FIELD_NUMBER = 15;
  /**
   * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
   * @return Whether the mSessionDeleteRes field is set.
   */
  @java.lang.Override
  public boolean hasMSessionDeleteRes() {
    return bodyCase_ == 15;
  }
  /**
   * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
   * @return The mSessionDeleteRes.
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MSessionDeleteRes getMSessionDeleteRes() {
    if (bodyCase_ == 15) {
       return (com.moomoo.moonect.proto.MSessionDeleteRes) body_;
    }
    return com.moomoo.moonect.proto.MSessionDeleteRes.getDefaultInstance();
  }
  /**
   * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
   */
  @java.lang.Override
  public com.moomoo.moonect.proto.MSessionDeleteResOrBuilder getMSessionDeleteResOrBuilder() {
    if (bodyCase_ == 15) {
       return (com.moomoo.moonect.proto.MSessionDeleteRes) body_;
    }
    return com.moomoo.moonect.proto.MSessionDeleteRes.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (mHeader_ != null) {
      output.writeMessage(1, getMHeader());
    }
    if (bodyCase_ == 2) {
      output.writeMessage(2, (com.moomoo.moonect.proto.MConnectReq) body_);
    }
    if (bodyCase_ == 3) {
      output.writeMessage(3, (com.moomoo.moonect.proto.MHeartBeatReq) body_);
    }
    if (bodyCase_ == 4) {
      output.writeMessage(4, (com.moomoo.moonect.proto.MSessionCreateReq) body_);
    }
    if (bodyCase_ == 5) {
      output.writeMessage(5, (com.moomoo.moonect.proto.MSessionDeleteReq) body_);
    }
    if (bodyCase_ == 10) {
      output.writeMessage(10, (com.moomoo.moonect.proto.MStatusNotify) body_);
    }
    if (bodyCase_ == 12) {
      output.writeMessage(12, (com.moomoo.moonect.proto.MConnectRes) body_);
    }
    if (bodyCase_ == 13) {
      output.writeMessage(13, (com.moomoo.moonect.proto.MHeartBeatRes) body_);
    }
    if (bodyCase_ == 14) {
      output.writeMessage(14, (com.moomoo.moonect.proto.MSessionCreateRes) body_);
    }
    if (bodyCase_ == 15) {
      output.writeMessage(15, (com.moomoo.moonect.proto.MSessionDeleteRes) body_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (mHeader_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMHeader());
    }
    if (bodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.moomoo.moonect.proto.MConnectReq) body_);
    }
    if (bodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.moomoo.moonect.proto.MHeartBeatReq) body_);
    }
    if (bodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.moomoo.moonect.proto.MSessionCreateReq) body_);
    }
    if (bodyCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.moomoo.moonect.proto.MSessionDeleteReq) body_);
    }
    if (bodyCase_ == 10) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, (com.moomoo.moonect.proto.MStatusNotify) body_);
    }
    if (bodyCase_ == 12) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, (com.moomoo.moonect.proto.MConnectRes) body_);
    }
    if (bodyCase_ == 13) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, (com.moomoo.moonect.proto.MHeartBeatRes) body_);
    }
    if (bodyCase_ == 14) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, (com.moomoo.moonect.proto.MSessionCreateRes) body_);
    }
    if (bodyCase_ == 15) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(15, (com.moomoo.moonect.proto.MSessionDeleteRes) body_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moomoo.moonect.proto.MMessage)) {
      return super.equals(obj);
    }
    com.moomoo.moonect.proto.MMessage other = (com.moomoo.moonect.proto.MMessage) obj;

    if (hasMHeader() != other.hasMHeader()) return false;
    if (hasMHeader()) {
      if (!getMHeader()
          .equals(other.getMHeader())) return false;
    }
    if (!getBodyCase().equals(other.getBodyCase())) return false;
    switch (bodyCase_) {
      case 2:
        if (!getMConnectReq()
            .equals(other.getMConnectReq())) return false;
        break;
      case 3:
        if (!getMHeartBeatReq()
            .equals(other.getMHeartBeatReq())) return false;
        break;
      case 4:
        if (!getMSessionCreateReq()
            .equals(other.getMSessionCreateReq())) return false;
        break;
      case 5:
        if (!getMSessionDeleteReq()
            .equals(other.getMSessionDeleteReq())) return false;
        break;
      case 10:
        if (!getMStatusNotify()
            .equals(other.getMStatusNotify())) return false;
        break;
      case 12:
        if (!getMConnectRes()
            .equals(other.getMConnectRes())) return false;
        break;
      case 13:
        if (!getMHeartBeatRes()
            .equals(other.getMHeartBeatRes())) return false;
        break;
      case 14:
        if (!getMSessionCreateRes()
            .equals(other.getMSessionCreateRes())) return false;
        break;
      case 15:
        if (!getMSessionDeleteRes()
            .equals(other.getMSessionDeleteRes())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMHeader()) {
      hash = (37 * hash) + MHEADER_FIELD_NUMBER;
      hash = (53 * hash) + getMHeader().hashCode();
    }
    switch (bodyCase_) {
      case 2:
        hash = (37 * hash) + MCONNECTREQ_FIELD_NUMBER;
        hash = (53 * hash) + getMConnectReq().hashCode();
        break;
      case 3:
        hash = (37 * hash) + MHEARTBEATREQ_FIELD_NUMBER;
        hash = (53 * hash) + getMHeartBeatReq().hashCode();
        break;
      case 4:
        hash = (37 * hash) + MSESSIONCREATEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getMSessionCreateReq().hashCode();
        break;
      case 5:
        hash = (37 * hash) + MSESSIONDELETEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getMSessionDeleteReq().hashCode();
        break;
      case 10:
        hash = (37 * hash) + MSTATUSNOTIFY_FIELD_NUMBER;
        hash = (53 * hash) + getMStatusNotify().hashCode();
        break;
      case 12:
        hash = (37 * hash) + MCONNECTRES_FIELD_NUMBER;
        hash = (53 * hash) + getMConnectRes().hashCode();
        break;
      case 13:
        hash = (37 * hash) + MHEARTBEATRES_FIELD_NUMBER;
        hash = (53 * hash) + getMHeartBeatRes().hashCode();
        break;
      case 14:
        hash = (37 * hash) + MSESSIONCREATERES_FIELD_NUMBER;
        hash = (53 * hash) + getMSessionCreateRes().hashCode();
        break;
      case 15:
        hash = (37 * hash) + MSESSIONDELETERES_FIELD_NUMBER;
        hash = (53 * hash) + getMSessionDeleteRes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moomoo.moonect.proto.MMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.moomoo.moonect.proto.MMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moomoo.moonect.proto.MMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moomoo.moonect.proto.MMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 필드 번호 할당 시 범위 : 1 - 536,870,911
   * 19,000 - 19,999 는 예약되어 있어 사용 자제
   * 주로 1-15 사용 권장 (1byte 소모)
   * </pre>
   *
   * Protobuf type {@code MMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MMessage)
      com.moomoo.moonect.proto.MMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moomoo.moonect.proto.MMessages.internal_static_MMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moomoo.moonect.proto.MMessages.internal_static_MMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moomoo.moonect.proto.MMessage.class, com.moomoo.moonect.proto.MMessage.Builder.class);
    }

    // Construct using com.moomoo.moonect.proto.MMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (mHeaderBuilder_ == null) {
        mHeader_ = null;
      } else {
        mHeader_ = null;
        mHeaderBuilder_ = null;
      }
      if (mConnectReqBuilder_ != null) {
        mConnectReqBuilder_.clear();
      }
      if (mHeartBeatReqBuilder_ != null) {
        mHeartBeatReqBuilder_.clear();
      }
      if (mSessionCreateReqBuilder_ != null) {
        mSessionCreateReqBuilder_.clear();
      }
      if (mSessionDeleteReqBuilder_ != null) {
        mSessionDeleteReqBuilder_.clear();
      }
      if (mStatusNotifyBuilder_ != null) {
        mStatusNotifyBuilder_.clear();
      }
      if (mConnectResBuilder_ != null) {
        mConnectResBuilder_.clear();
      }
      if (mHeartBeatResBuilder_ != null) {
        mHeartBeatResBuilder_.clear();
      }
      if (mSessionCreateResBuilder_ != null) {
        mSessionCreateResBuilder_.clear();
      }
      if (mSessionDeleteResBuilder_ != null) {
        mSessionDeleteResBuilder_.clear();
      }
      bodyCase_ = 0;
      body_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moomoo.moonect.proto.MMessages.internal_static_MMessage_descriptor;
    }

    @java.lang.Override
    public com.moomoo.moonect.proto.MMessage getDefaultInstanceForType() {
      return com.moomoo.moonect.proto.MMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.moomoo.moonect.proto.MMessage build() {
      com.moomoo.moonect.proto.MMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moomoo.moonect.proto.MMessage buildPartial() {
      com.moomoo.moonect.proto.MMessage result = new com.moomoo.moonect.proto.MMessage(this);
      if (mHeaderBuilder_ == null) {
        result.mHeader_ = mHeader_;
      } else {
        result.mHeader_ = mHeaderBuilder_.build();
      }
      if (bodyCase_ == 2) {
        if (mConnectReqBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mConnectReqBuilder_.build();
        }
      }
      if (bodyCase_ == 3) {
        if (mHeartBeatReqBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mHeartBeatReqBuilder_.build();
        }
      }
      if (bodyCase_ == 4) {
        if (mSessionCreateReqBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mSessionCreateReqBuilder_.build();
        }
      }
      if (bodyCase_ == 5) {
        if (mSessionDeleteReqBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mSessionDeleteReqBuilder_.build();
        }
      }
      if (bodyCase_ == 10) {
        if (mStatusNotifyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mStatusNotifyBuilder_.build();
        }
      }
      if (bodyCase_ == 12) {
        if (mConnectResBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mConnectResBuilder_.build();
        }
      }
      if (bodyCase_ == 13) {
        if (mHeartBeatResBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mHeartBeatResBuilder_.build();
        }
      }
      if (bodyCase_ == 14) {
        if (mSessionCreateResBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mSessionCreateResBuilder_.build();
        }
      }
      if (bodyCase_ == 15) {
        if (mSessionDeleteResBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = mSessionDeleteResBuilder_.build();
        }
      }
      result.bodyCase_ = bodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moomoo.moonect.proto.MMessage) {
        return mergeFrom((com.moomoo.moonect.proto.MMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moomoo.moonect.proto.MMessage other) {
      if (other == com.moomoo.moonect.proto.MMessage.getDefaultInstance()) return this;
      if (other.hasMHeader()) {
        mergeMHeader(other.getMHeader());
      }
      switch (other.getBodyCase()) {
        case MCONNECTREQ: {
          mergeMConnectReq(other.getMConnectReq());
          break;
        }
        case MHEARTBEATREQ: {
          mergeMHeartBeatReq(other.getMHeartBeatReq());
          break;
        }
        case MSESSIONCREATEREQ: {
          mergeMSessionCreateReq(other.getMSessionCreateReq());
          break;
        }
        case MSESSIONDELETEREQ: {
          mergeMSessionDeleteReq(other.getMSessionDeleteReq());
          break;
        }
        case MSTATUSNOTIFY: {
          mergeMStatusNotify(other.getMStatusNotify());
          break;
        }
        case MCONNECTRES: {
          mergeMConnectRes(other.getMConnectRes());
          break;
        }
        case MHEARTBEATRES: {
          mergeMHeartBeatRes(other.getMHeartBeatRes());
          break;
        }
        case MSESSIONCREATERES: {
          mergeMSessionCreateRes(other.getMSessionCreateRes());
          break;
        }
        case MSESSIONDELETERES: {
          mergeMSessionDeleteRes(other.getMSessionDeleteRes());
          break;
        }
        case BODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getMHeaderFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getMConnectReqFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMHeartBeatReqFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getMSessionCreateReqFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getMSessionDeleteReqFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 5;
              break;
            } // case 42
            case 82: {
              input.readMessage(
                  getMStatusNotifyFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 10;
              break;
            } // case 82
            case 98: {
              input.readMessage(
                  getMConnectResFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 12;
              break;
            } // case 98
            case 106: {
              input.readMessage(
                  getMHeartBeatResFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 13;
              break;
            } // case 106
            case 114: {
              input.readMessage(
                  getMSessionCreateResFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 14;
              break;
            } // case 114
            case 122: {
              input.readMessage(
                  getMSessionDeleteResFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 15;
              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public BodyCase
        getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public Builder clearBody() {
      bodyCase_ = 0;
      body_ = null;
      onChanged();
      return this;
    }


    private com.moomoo.moonect.proto.MHeader mHeader_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MHeader, com.moomoo.moonect.proto.MHeader.Builder, com.moomoo.moonect.proto.MHeaderOrBuilder> mHeaderBuilder_;
    /**
     * <code>.MHeader mHeader = 1;</code>
     * @return Whether the mHeader field is set.
     */
    public boolean hasMHeader() {
      return mHeaderBuilder_ != null || mHeader_ != null;
    }
    /**
     * <code>.MHeader mHeader = 1;</code>
     * @return The mHeader.
     */
    public com.moomoo.moonect.proto.MHeader getMHeader() {
      if (mHeaderBuilder_ == null) {
        return mHeader_ == null ? com.moomoo.moonect.proto.MHeader.getDefaultInstance() : mHeader_;
      } else {
        return mHeaderBuilder_.getMessage();
      }
    }
    /**
     * <code>.MHeader mHeader = 1;</code>
     */
    public Builder setMHeader(com.moomoo.moonect.proto.MHeader value) {
      if (mHeaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        mHeader_ = value;
        onChanged();
      } else {
        mHeaderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.MHeader mHeader = 1;</code>
     */
    public Builder setMHeader(
        com.moomoo.moonect.proto.MHeader.Builder builderForValue) {
      if (mHeaderBuilder_ == null) {
        mHeader_ = builderForValue.build();
        onChanged();
      } else {
        mHeaderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.MHeader mHeader = 1;</code>
     */
    public Builder mergeMHeader(com.moomoo.moonect.proto.MHeader value) {
      if (mHeaderBuilder_ == null) {
        if (mHeader_ != null) {
          mHeader_ =
            com.moomoo.moonect.proto.MHeader.newBuilder(mHeader_).mergeFrom(value).buildPartial();
        } else {
          mHeader_ = value;
        }
        onChanged();
      } else {
        mHeaderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.MHeader mHeader = 1;</code>
     */
    public Builder clearMHeader() {
      if (mHeaderBuilder_ == null) {
        mHeader_ = null;
        onChanged();
      } else {
        mHeader_ = null;
        mHeaderBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.MHeader mHeader = 1;</code>
     */
    public com.moomoo.moonect.proto.MHeader.Builder getMHeaderBuilder() {
      
      onChanged();
      return getMHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.MHeader mHeader = 1;</code>
     */
    public com.moomoo.moonect.proto.MHeaderOrBuilder getMHeaderOrBuilder() {
      if (mHeaderBuilder_ != null) {
        return mHeaderBuilder_.getMessageOrBuilder();
      } else {
        return mHeader_ == null ?
            com.moomoo.moonect.proto.MHeader.getDefaultInstance() : mHeader_;
      }
    }
    /**
     * <code>.MHeader mHeader = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MHeader, com.moomoo.moonect.proto.MHeader.Builder, com.moomoo.moonect.proto.MHeaderOrBuilder> 
        getMHeaderFieldBuilder() {
      if (mHeaderBuilder_ == null) {
        mHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MHeader, com.moomoo.moonect.proto.MHeader.Builder, com.moomoo.moonect.proto.MHeaderOrBuilder>(
                getMHeader(),
                getParentForChildren(),
                isClean());
        mHeader_ = null;
      }
      return mHeaderBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MConnectReq, com.moomoo.moonect.proto.MConnectReq.Builder, com.moomoo.moonect.proto.MConnectReqOrBuilder> mConnectReqBuilder_;
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     * @return Whether the mConnectReq field is set.
     */
    @java.lang.Override
    public boolean hasMConnectReq() {
      return bodyCase_ == 2;
    }
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     * @return The mConnectReq.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MConnectReq getMConnectReq() {
      if (mConnectReqBuilder_ == null) {
        if (bodyCase_ == 2) {
          return (com.moomoo.moonect.proto.MConnectReq) body_;
        }
        return com.moomoo.moonect.proto.MConnectReq.getDefaultInstance();
      } else {
        if (bodyCase_ == 2) {
          return mConnectReqBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MConnectReq.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     */
    public Builder setMConnectReq(com.moomoo.moonect.proto.MConnectReq value) {
      if (mConnectReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mConnectReqBuilder_.setMessage(value);
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     */
    public Builder setMConnectReq(
        com.moomoo.moonect.proto.MConnectReq.Builder builderForValue) {
      if (mConnectReqBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mConnectReqBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     */
    public Builder mergeMConnectReq(com.moomoo.moonect.proto.MConnectReq value) {
      if (mConnectReqBuilder_ == null) {
        if (bodyCase_ == 2 &&
            body_ != com.moomoo.moonect.proto.MConnectReq.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MConnectReq.newBuilder((com.moomoo.moonect.proto.MConnectReq) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 2) {
          mConnectReqBuilder_.mergeFrom(value);
        } else {
          mConnectReqBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     */
    public Builder clearMConnectReq() {
      if (mConnectReqBuilder_ == null) {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
        }
        mConnectReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     */
    public com.moomoo.moonect.proto.MConnectReq.Builder getMConnectReqBuilder() {
      return getMConnectReqFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MConnectReqOrBuilder getMConnectReqOrBuilder() {
      if ((bodyCase_ == 2) && (mConnectReqBuilder_ != null)) {
        return mConnectReqBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 2) {
          return (com.moomoo.moonect.proto.MConnectReq) body_;
        }
        return com.moomoo.moonect.proto.MConnectReq.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Requests
     * </pre>
     *
     * <code>.MConnectReq mConnectReq = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MConnectReq, com.moomoo.moonect.proto.MConnectReq.Builder, com.moomoo.moonect.proto.MConnectReqOrBuilder> 
        getMConnectReqFieldBuilder() {
      if (mConnectReqBuilder_ == null) {
        if (!(bodyCase_ == 2)) {
          body_ = com.moomoo.moonect.proto.MConnectReq.getDefaultInstance();
        }
        mConnectReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MConnectReq, com.moomoo.moonect.proto.MConnectReq.Builder, com.moomoo.moonect.proto.MConnectReqOrBuilder>(
                (com.moomoo.moonect.proto.MConnectReq) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 2;
      onChanged();;
      return mConnectReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MHeartBeatReq, com.moomoo.moonect.proto.MHeartBeatReq.Builder, com.moomoo.moonect.proto.MHeartBeatReqOrBuilder> mHeartBeatReqBuilder_;
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     * @return Whether the mHeartBeatReq field is set.
     */
    @java.lang.Override
    public boolean hasMHeartBeatReq() {
      return bodyCase_ == 3;
    }
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     * @return The mHeartBeatReq.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MHeartBeatReq getMHeartBeatReq() {
      if (mHeartBeatReqBuilder_ == null) {
        if (bodyCase_ == 3) {
          return (com.moomoo.moonect.proto.MHeartBeatReq) body_;
        }
        return com.moomoo.moonect.proto.MHeartBeatReq.getDefaultInstance();
      } else {
        if (bodyCase_ == 3) {
          return mHeartBeatReqBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MHeartBeatReq.getDefaultInstance();
      }
    }
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     */
    public Builder setMHeartBeatReq(com.moomoo.moonect.proto.MHeartBeatReq value) {
      if (mHeartBeatReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mHeartBeatReqBuilder_.setMessage(value);
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     */
    public Builder setMHeartBeatReq(
        com.moomoo.moonect.proto.MHeartBeatReq.Builder builderForValue) {
      if (mHeartBeatReqBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mHeartBeatReqBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     */
    public Builder mergeMHeartBeatReq(com.moomoo.moonect.proto.MHeartBeatReq value) {
      if (mHeartBeatReqBuilder_ == null) {
        if (bodyCase_ == 3 &&
            body_ != com.moomoo.moonect.proto.MHeartBeatReq.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MHeartBeatReq.newBuilder((com.moomoo.moonect.proto.MHeartBeatReq) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 3) {
          mHeartBeatReqBuilder_.mergeFrom(value);
        } else {
          mHeartBeatReqBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     */
    public Builder clearMHeartBeatReq() {
      if (mHeartBeatReqBuilder_ == null) {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
        }
        mHeartBeatReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     */
    public com.moomoo.moonect.proto.MHeartBeatReq.Builder getMHeartBeatReqBuilder() {
      return getMHeartBeatReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MHeartBeatReqOrBuilder getMHeartBeatReqOrBuilder() {
      if ((bodyCase_ == 3) && (mHeartBeatReqBuilder_ != null)) {
        return mHeartBeatReqBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 3) {
          return (com.moomoo.moonect.proto.MHeartBeatReq) body_;
        }
        return com.moomoo.moonect.proto.MHeartBeatReq.getDefaultInstance();
      }
    }
    /**
     * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MHeartBeatReq, com.moomoo.moonect.proto.MHeartBeatReq.Builder, com.moomoo.moonect.proto.MHeartBeatReqOrBuilder> 
        getMHeartBeatReqFieldBuilder() {
      if (mHeartBeatReqBuilder_ == null) {
        if (!(bodyCase_ == 3)) {
          body_ = com.moomoo.moonect.proto.MHeartBeatReq.getDefaultInstance();
        }
        mHeartBeatReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MHeartBeatReq, com.moomoo.moonect.proto.MHeartBeatReq.Builder, com.moomoo.moonect.proto.MHeartBeatReqOrBuilder>(
                (com.moomoo.moonect.proto.MHeartBeatReq) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 3;
      onChanged();;
      return mHeartBeatReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MSessionCreateReq, com.moomoo.moonect.proto.MSessionCreateReq.Builder, com.moomoo.moonect.proto.MSessionCreateReqOrBuilder> mSessionCreateReqBuilder_;
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     * @return Whether the mSessionCreateReq field is set.
     */
    @java.lang.Override
    public boolean hasMSessionCreateReq() {
      return bodyCase_ == 4;
    }
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     * @return The mSessionCreateReq.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MSessionCreateReq getMSessionCreateReq() {
      if (mSessionCreateReqBuilder_ == null) {
        if (bodyCase_ == 4) {
          return (com.moomoo.moonect.proto.MSessionCreateReq) body_;
        }
        return com.moomoo.moonect.proto.MSessionCreateReq.getDefaultInstance();
      } else {
        if (bodyCase_ == 4) {
          return mSessionCreateReqBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MSessionCreateReq.getDefaultInstance();
      }
    }
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     */
    public Builder setMSessionCreateReq(com.moomoo.moonect.proto.MSessionCreateReq value) {
      if (mSessionCreateReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mSessionCreateReqBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     */
    public Builder setMSessionCreateReq(
        com.moomoo.moonect.proto.MSessionCreateReq.Builder builderForValue) {
      if (mSessionCreateReqBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mSessionCreateReqBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     */
    public Builder mergeMSessionCreateReq(com.moomoo.moonect.proto.MSessionCreateReq value) {
      if (mSessionCreateReqBuilder_ == null) {
        if (bodyCase_ == 4 &&
            body_ != com.moomoo.moonect.proto.MSessionCreateReq.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MSessionCreateReq.newBuilder((com.moomoo.moonect.proto.MSessionCreateReq) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 4) {
          mSessionCreateReqBuilder_.mergeFrom(value);
        } else {
          mSessionCreateReqBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     */
    public Builder clearMSessionCreateReq() {
      if (mSessionCreateReqBuilder_ == null) {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
        }
        mSessionCreateReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     */
    public com.moomoo.moonect.proto.MSessionCreateReq.Builder getMSessionCreateReqBuilder() {
      return getMSessionCreateReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MSessionCreateReqOrBuilder getMSessionCreateReqOrBuilder() {
      if ((bodyCase_ == 4) && (mSessionCreateReqBuilder_ != null)) {
        return mSessionCreateReqBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 4) {
          return (com.moomoo.moonect.proto.MSessionCreateReq) body_;
        }
        return com.moomoo.moonect.proto.MSessionCreateReq.getDefaultInstance();
      }
    }
    /**
     * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MSessionCreateReq, com.moomoo.moonect.proto.MSessionCreateReq.Builder, com.moomoo.moonect.proto.MSessionCreateReqOrBuilder> 
        getMSessionCreateReqFieldBuilder() {
      if (mSessionCreateReqBuilder_ == null) {
        if (!(bodyCase_ == 4)) {
          body_ = com.moomoo.moonect.proto.MSessionCreateReq.getDefaultInstance();
        }
        mSessionCreateReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MSessionCreateReq, com.moomoo.moonect.proto.MSessionCreateReq.Builder, com.moomoo.moonect.proto.MSessionCreateReqOrBuilder>(
                (com.moomoo.moonect.proto.MSessionCreateReq) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 4;
      onChanged();;
      return mSessionCreateReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MSessionDeleteReq, com.moomoo.moonect.proto.MSessionDeleteReq.Builder, com.moomoo.moonect.proto.MSessionDeleteReqOrBuilder> mSessionDeleteReqBuilder_;
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     * @return Whether the mSessionDeleteReq field is set.
     */
    @java.lang.Override
    public boolean hasMSessionDeleteReq() {
      return bodyCase_ == 5;
    }
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     * @return The mSessionDeleteReq.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MSessionDeleteReq getMSessionDeleteReq() {
      if (mSessionDeleteReqBuilder_ == null) {
        if (bodyCase_ == 5) {
          return (com.moomoo.moonect.proto.MSessionDeleteReq) body_;
        }
        return com.moomoo.moonect.proto.MSessionDeleteReq.getDefaultInstance();
      } else {
        if (bodyCase_ == 5) {
          return mSessionDeleteReqBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MSessionDeleteReq.getDefaultInstance();
      }
    }
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     */
    public Builder setMSessionDeleteReq(com.moomoo.moonect.proto.MSessionDeleteReq value) {
      if (mSessionDeleteReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mSessionDeleteReqBuilder_.setMessage(value);
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     */
    public Builder setMSessionDeleteReq(
        com.moomoo.moonect.proto.MSessionDeleteReq.Builder builderForValue) {
      if (mSessionDeleteReqBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mSessionDeleteReqBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     */
    public Builder mergeMSessionDeleteReq(com.moomoo.moonect.proto.MSessionDeleteReq value) {
      if (mSessionDeleteReqBuilder_ == null) {
        if (bodyCase_ == 5 &&
            body_ != com.moomoo.moonect.proto.MSessionDeleteReq.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MSessionDeleteReq.newBuilder((com.moomoo.moonect.proto.MSessionDeleteReq) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 5) {
          mSessionDeleteReqBuilder_.mergeFrom(value);
        } else {
          mSessionDeleteReqBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 5;
      return this;
    }
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     */
    public Builder clearMSessionDeleteReq() {
      if (mSessionDeleteReqBuilder_ == null) {
        if (bodyCase_ == 5) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 5) {
          bodyCase_ = 0;
          body_ = null;
        }
        mSessionDeleteReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     */
    public com.moomoo.moonect.proto.MSessionDeleteReq.Builder getMSessionDeleteReqBuilder() {
      return getMSessionDeleteReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MSessionDeleteReqOrBuilder getMSessionDeleteReqOrBuilder() {
      if ((bodyCase_ == 5) && (mSessionDeleteReqBuilder_ != null)) {
        return mSessionDeleteReqBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 5) {
          return (com.moomoo.moonect.proto.MSessionDeleteReq) body_;
        }
        return com.moomoo.moonect.proto.MSessionDeleteReq.getDefaultInstance();
      }
    }
    /**
     * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MSessionDeleteReq, com.moomoo.moonect.proto.MSessionDeleteReq.Builder, com.moomoo.moonect.proto.MSessionDeleteReqOrBuilder> 
        getMSessionDeleteReqFieldBuilder() {
      if (mSessionDeleteReqBuilder_ == null) {
        if (!(bodyCase_ == 5)) {
          body_ = com.moomoo.moonect.proto.MSessionDeleteReq.getDefaultInstance();
        }
        mSessionDeleteReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MSessionDeleteReq, com.moomoo.moonect.proto.MSessionDeleteReq.Builder, com.moomoo.moonect.proto.MSessionDeleteReqOrBuilder>(
                (com.moomoo.moonect.proto.MSessionDeleteReq) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 5;
      onChanged();;
      return mSessionDeleteReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MStatusNotify, com.moomoo.moonect.proto.MStatusNotify.Builder, com.moomoo.moonect.proto.MStatusNotifyOrBuilder> mStatusNotifyBuilder_;
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     * @return Whether the mStatusNotify field is set.
     */
    @java.lang.Override
    public boolean hasMStatusNotify() {
      return bodyCase_ == 10;
    }
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     * @return The mStatusNotify.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MStatusNotify getMStatusNotify() {
      if (mStatusNotifyBuilder_ == null) {
        if (bodyCase_ == 10) {
          return (com.moomoo.moonect.proto.MStatusNotify) body_;
        }
        return com.moomoo.moonect.proto.MStatusNotify.getDefaultInstance();
      } else {
        if (bodyCase_ == 10) {
          return mStatusNotifyBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MStatusNotify.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     */
    public Builder setMStatusNotify(com.moomoo.moonect.proto.MStatusNotify value) {
      if (mStatusNotifyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mStatusNotifyBuilder_.setMessage(value);
      }
      bodyCase_ = 10;
      return this;
    }
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     */
    public Builder setMStatusNotify(
        com.moomoo.moonect.proto.MStatusNotify.Builder builderForValue) {
      if (mStatusNotifyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mStatusNotifyBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 10;
      return this;
    }
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     */
    public Builder mergeMStatusNotify(com.moomoo.moonect.proto.MStatusNotify value) {
      if (mStatusNotifyBuilder_ == null) {
        if (bodyCase_ == 10 &&
            body_ != com.moomoo.moonect.proto.MStatusNotify.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MStatusNotify.newBuilder((com.moomoo.moonect.proto.MStatusNotify) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 10) {
          mStatusNotifyBuilder_.mergeFrom(value);
        } else {
          mStatusNotifyBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 10;
      return this;
    }
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     */
    public Builder clearMStatusNotify() {
      if (mStatusNotifyBuilder_ == null) {
        if (bodyCase_ == 10) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 10) {
          bodyCase_ = 0;
          body_ = null;
        }
        mStatusNotifyBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     */
    public com.moomoo.moonect.proto.MStatusNotify.Builder getMStatusNotifyBuilder() {
      return getMStatusNotifyFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MStatusNotifyOrBuilder getMStatusNotifyOrBuilder() {
      if ((bodyCase_ == 10) && (mStatusNotifyBuilder_ != null)) {
        return mStatusNotifyBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 10) {
          return (com.moomoo.moonect.proto.MStatusNotify) body_;
        }
        return com.moomoo.moonect.proto.MStatusNotify.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Notices
     * </pre>
     *
     * <code>.MStatusNotify mStatusNotify = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MStatusNotify, com.moomoo.moonect.proto.MStatusNotify.Builder, com.moomoo.moonect.proto.MStatusNotifyOrBuilder> 
        getMStatusNotifyFieldBuilder() {
      if (mStatusNotifyBuilder_ == null) {
        if (!(bodyCase_ == 10)) {
          body_ = com.moomoo.moonect.proto.MStatusNotify.getDefaultInstance();
        }
        mStatusNotifyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MStatusNotify, com.moomoo.moonect.proto.MStatusNotify.Builder, com.moomoo.moonect.proto.MStatusNotifyOrBuilder>(
                (com.moomoo.moonect.proto.MStatusNotify) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 10;
      onChanged();;
      return mStatusNotifyBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MConnectRes, com.moomoo.moonect.proto.MConnectRes.Builder, com.moomoo.moonect.proto.MConnectResOrBuilder> mConnectResBuilder_;
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     * @return Whether the mConnectRes field is set.
     */
    @java.lang.Override
    public boolean hasMConnectRes() {
      return bodyCase_ == 12;
    }
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     * @return The mConnectRes.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MConnectRes getMConnectRes() {
      if (mConnectResBuilder_ == null) {
        if (bodyCase_ == 12) {
          return (com.moomoo.moonect.proto.MConnectRes) body_;
        }
        return com.moomoo.moonect.proto.MConnectRes.getDefaultInstance();
      } else {
        if (bodyCase_ == 12) {
          return mConnectResBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MConnectRes.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     */
    public Builder setMConnectRes(com.moomoo.moonect.proto.MConnectRes value) {
      if (mConnectResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mConnectResBuilder_.setMessage(value);
      }
      bodyCase_ = 12;
      return this;
    }
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     */
    public Builder setMConnectRes(
        com.moomoo.moonect.proto.MConnectRes.Builder builderForValue) {
      if (mConnectResBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mConnectResBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 12;
      return this;
    }
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     */
    public Builder mergeMConnectRes(com.moomoo.moonect.proto.MConnectRes value) {
      if (mConnectResBuilder_ == null) {
        if (bodyCase_ == 12 &&
            body_ != com.moomoo.moonect.proto.MConnectRes.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MConnectRes.newBuilder((com.moomoo.moonect.proto.MConnectRes) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 12) {
          mConnectResBuilder_.mergeFrom(value);
        } else {
          mConnectResBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 12;
      return this;
    }
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     */
    public Builder clearMConnectRes() {
      if (mConnectResBuilder_ == null) {
        if (bodyCase_ == 12) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 12) {
          bodyCase_ = 0;
          body_ = null;
        }
        mConnectResBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     */
    public com.moomoo.moonect.proto.MConnectRes.Builder getMConnectResBuilder() {
      return getMConnectResFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MConnectResOrBuilder getMConnectResOrBuilder() {
      if ((bodyCase_ == 12) && (mConnectResBuilder_ != null)) {
        return mConnectResBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 12) {
          return (com.moomoo.moonect.proto.MConnectRes) body_;
        }
        return com.moomoo.moonect.proto.MConnectRes.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Responses
     * </pre>
     *
     * <code>.MConnectRes mConnectRes = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MConnectRes, com.moomoo.moonect.proto.MConnectRes.Builder, com.moomoo.moonect.proto.MConnectResOrBuilder> 
        getMConnectResFieldBuilder() {
      if (mConnectResBuilder_ == null) {
        if (!(bodyCase_ == 12)) {
          body_ = com.moomoo.moonect.proto.MConnectRes.getDefaultInstance();
        }
        mConnectResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MConnectRes, com.moomoo.moonect.proto.MConnectRes.Builder, com.moomoo.moonect.proto.MConnectResOrBuilder>(
                (com.moomoo.moonect.proto.MConnectRes) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 12;
      onChanged();;
      return mConnectResBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MHeartBeatRes, com.moomoo.moonect.proto.MHeartBeatRes.Builder, com.moomoo.moonect.proto.MHeartBeatResOrBuilder> mHeartBeatResBuilder_;
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     * @return Whether the mHeartBeatRes field is set.
     */
    @java.lang.Override
    public boolean hasMHeartBeatRes() {
      return bodyCase_ == 13;
    }
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     * @return The mHeartBeatRes.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MHeartBeatRes getMHeartBeatRes() {
      if (mHeartBeatResBuilder_ == null) {
        if (bodyCase_ == 13) {
          return (com.moomoo.moonect.proto.MHeartBeatRes) body_;
        }
        return com.moomoo.moonect.proto.MHeartBeatRes.getDefaultInstance();
      } else {
        if (bodyCase_ == 13) {
          return mHeartBeatResBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MHeartBeatRes.getDefaultInstance();
      }
    }
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     */
    public Builder setMHeartBeatRes(com.moomoo.moonect.proto.MHeartBeatRes value) {
      if (mHeartBeatResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mHeartBeatResBuilder_.setMessage(value);
      }
      bodyCase_ = 13;
      return this;
    }
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     */
    public Builder setMHeartBeatRes(
        com.moomoo.moonect.proto.MHeartBeatRes.Builder builderForValue) {
      if (mHeartBeatResBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mHeartBeatResBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 13;
      return this;
    }
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     */
    public Builder mergeMHeartBeatRes(com.moomoo.moonect.proto.MHeartBeatRes value) {
      if (mHeartBeatResBuilder_ == null) {
        if (bodyCase_ == 13 &&
            body_ != com.moomoo.moonect.proto.MHeartBeatRes.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MHeartBeatRes.newBuilder((com.moomoo.moonect.proto.MHeartBeatRes) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 13) {
          mHeartBeatResBuilder_.mergeFrom(value);
        } else {
          mHeartBeatResBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 13;
      return this;
    }
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     */
    public Builder clearMHeartBeatRes() {
      if (mHeartBeatResBuilder_ == null) {
        if (bodyCase_ == 13) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 13) {
          bodyCase_ = 0;
          body_ = null;
        }
        mHeartBeatResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     */
    public com.moomoo.moonect.proto.MHeartBeatRes.Builder getMHeartBeatResBuilder() {
      return getMHeartBeatResFieldBuilder().getBuilder();
    }
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MHeartBeatResOrBuilder getMHeartBeatResOrBuilder() {
      if ((bodyCase_ == 13) && (mHeartBeatResBuilder_ != null)) {
        return mHeartBeatResBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 13) {
          return (com.moomoo.moonect.proto.MHeartBeatRes) body_;
        }
        return com.moomoo.moonect.proto.MHeartBeatRes.getDefaultInstance();
      }
    }
    /**
     * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MHeartBeatRes, com.moomoo.moonect.proto.MHeartBeatRes.Builder, com.moomoo.moonect.proto.MHeartBeatResOrBuilder> 
        getMHeartBeatResFieldBuilder() {
      if (mHeartBeatResBuilder_ == null) {
        if (!(bodyCase_ == 13)) {
          body_ = com.moomoo.moonect.proto.MHeartBeatRes.getDefaultInstance();
        }
        mHeartBeatResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MHeartBeatRes, com.moomoo.moonect.proto.MHeartBeatRes.Builder, com.moomoo.moonect.proto.MHeartBeatResOrBuilder>(
                (com.moomoo.moonect.proto.MHeartBeatRes) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 13;
      onChanged();;
      return mHeartBeatResBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MSessionCreateRes, com.moomoo.moonect.proto.MSessionCreateRes.Builder, com.moomoo.moonect.proto.MSessionCreateResOrBuilder> mSessionCreateResBuilder_;
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     * @return Whether the mSessionCreateRes field is set.
     */
    @java.lang.Override
    public boolean hasMSessionCreateRes() {
      return bodyCase_ == 14;
    }
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     * @return The mSessionCreateRes.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MSessionCreateRes getMSessionCreateRes() {
      if (mSessionCreateResBuilder_ == null) {
        if (bodyCase_ == 14) {
          return (com.moomoo.moonect.proto.MSessionCreateRes) body_;
        }
        return com.moomoo.moonect.proto.MSessionCreateRes.getDefaultInstance();
      } else {
        if (bodyCase_ == 14) {
          return mSessionCreateResBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MSessionCreateRes.getDefaultInstance();
      }
    }
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     */
    public Builder setMSessionCreateRes(com.moomoo.moonect.proto.MSessionCreateRes value) {
      if (mSessionCreateResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mSessionCreateResBuilder_.setMessage(value);
      }
      bodyCase_ = 14;
      return this;
    }
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     */
    public Builder setMSessionCreateRes(
        com.moomoo.moonect.proto.MSessionCreateRes.Builder builderForValue) {
      if (mSessionCreateResBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mSessionCreateResBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 14;
      return this;
    }
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     */
    public Builder mergeMSessionCreateRes(com.moomoo.moonect.proto.MSessionCreateRes value) {
      if (mSessionCreateResBuilder_ == null) {
        if (bodyCase_ == 14 &&
            body_ != com.moomoo.moonect.proto.MSessionCreateRes.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MSessionCreateRes.newBuilder((com.moomoo.moonect.proto.MSessionCreateRes) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 14) {
          mSessionCreateResBuilder_.mergeFrom(value);
        } else {
          mSessionCreateResBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 14;
      return this;
    }
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     */
    public Builder clearMSessionCreateRes() {
      if (mSessionCreateResBuilder_ == null) {
        if (bodyCase_ == 14) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 14) {
          bodyCase_ = 0;
          body_ = null;
        }
        mSessionCreateResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     */
    public com.moomoo.moonect.proto.MSessionCreateRes.Builder getMSessionCreateResBuilder() {
      return getMSessionCreateResFieldBuilder().getBuilder();
    }
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MSessionCreateResOrBuilder getMSessionCreateResOrBuilder() {
      if ((bodyCase_ == 14) && (mSessionCreateResBuilder_ != null)) {
        return mSessionCreateResBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 14) {
          return (com.moomoo.moonect.proto.MSessionCreateRes) body_;
        }
        return com.moomoo.moonect.proto.MSessionCreateRes.getDefaultInstance();
      }
    }
    /**
     * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MSessionCreateRes, com.moomoo.moonect.proto.MSessionCreateRes.Builder, com.moomoo.moonect.proto.MSessionCreateResOrBuilder> 
        getMSessionCreateResFieldBuilder() {
      if (mSessionCreateResBuilder_ == null) {
        if (!(bodyCase_ == 14)) {
          body_ = com.moomoo.moonect.proto.MSessionCreateRes.getDefaultInstance();
        }
        mSessionCreateResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MSessionCreateRes, com.moomoo.moonect.proto.MSessionCreateRes.Builder, com.moomoo.moonect.proto.MSessionCreateResOrBuilder>(
                (com.moomoo.moonect.proto.MSessionCreateRes) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 14;
      onChanged();;
      return mSessionCreateResBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MSessionDeleteRes, com.moomoo.moonect.proto.MSessionDeleteRes.Builder, com.moomoo.moonect.proto.MSessionDeleteResOrBuilder> mSessionDeleteResBuilder_;
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     * @return Whether the mSessionDeleteRes field is set.
     */
    @java.lang.Override
    public boolean hasMSessionDeleteRes() {
      return bodyCase_ == 15;
    }
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     * @return The mSessionDeleteRes.
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MSessionDeleteRes getMSessionDeleteRes() {
      if (mSessionDeleteResBuilder_ == null) {
        if (bodyCase_ == 15) {
          return (com.moomoo.moonect.proto.MSessionDeleteRes) body_;
        }
        return com.moomoo.moonect.proto.MSessionDeleteRes.getDefaultInstance();
      } else {
        if (bodyCase_ == 15) {
          return mSessionDeleteResBuilder_.getMessage();
        }
        return com.moomoo.moonect.proto.MSessionDeleteRes.getDefaultInstance();
      }
    }
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     */
    public Builder setMSessionDeleteRes(com.moomoo.moonect.proto.MSessionDeleteRes value) {
      if (mSessionDeleteResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        mSessionDeleteResBuilder_.setMessage(value);
      }
      bodyCase_ = 15;
      return this;
    }
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     */
    public Builder setMSessionDeleteRes(
        com.moomoo.moonect.proto.MSessionDeleteRes.Builder builderForValue) {
      if (mSessionDeleteResBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        mSessionDeleteResBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 15;
      return this;
    }
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     */
    public Builder mergeMSessionDeleteRes(com.moomoo.moonect.proto.MSessionDeleteRes value) {
      if (mSessionDeleteResBuilder_ == null) {
        if (bodyCase_ == 15 &&
            body_ != com.moomoo.moonect.proto.MSessionDeleteRes.getDefaultInstance()) {
          body_ = com.moomoo.moonect.proto.MSessionDeleteRes.newBuilder((com.moomoo.moonect.proto.MSessionDeleteRes) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 15) {
          mSessionDeleteResBuilder_.mergeFrom(value);
        } else {
          mSessionDeleteResBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 15;
      return this;
    }
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     */
    public Builder clearMSessionDeleteRes() {
      if (mSessionDeleteResBuilder_ == null) {
        if (bodyCase_ == 15) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 15) {
          bodyCase_ = 0;
          body_ = null;
        }
        mSessionDeleteResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     */
    public com.moomoo.moonect.proto.MSessionDeleteRes.Builder getMSessionDeleteResBuilder() {
      return getMSessionDeleteResFieldBuilder().getBuilder();
    }
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     */
    @java.lang.Override
    public com.moomoo.moonect.proto.MSessionDeleteResOrBuilder getMSessionDeleteResOrBuilder() {
      if ((bodyCase_ == 15) && (mSessionDeleteResBuilder_ != null)) {
        return mSessionDeleteResBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 15) {
          return (com.moomoo.moonect.proto.MSessionDeleteRes) body_;
        }
        return com.moomoo.moonect.proto.MSessionDeleteRes.getDefaultInstance();
      }
    }
    /**
     * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moomoo.moonect.proto.MSessionDeleteRes, com.moomoo.moonect.proto.MSessionDeleteRes.Builder, com.moomoo.moonect.proto.MSessionDeleteResOrBuilder> 
        getMSessionDeleteResFieldBuilder() {
      if (mSessionDeleteResBuilder_ == null) {
        if (!(bodyCase_ == 15)) {
          body_ = com.moomoo.moonect.proto.MSessionDeleteRes.getDefaultInstance();
        }
        mSessionDeleteResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moomoo.moonect.proto.MSessionDeleteRes, com.moomoo.moonect.proto.MSessionDeleteRes.Builder, com.moomoo.moonect.proto.MSessionDeleteResOrBuilder>(
                (com.moomoo.moonect.proto.MSessionDeleteRes) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 15;
      onChanged();;
      return mSessionDeleteResBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MMessage)
  }

  // @@protoc_insertion_point(class_scope:MMessage)
  private static final com.moomoo.moonect.proto.MMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moomoo.moonect.proto.MMessage();
  }

  public static com.moomoo.moonect.proto.MMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MMessage>
      PARSER = new com.google.protobuf.AbstractParser<MMessage>() {
    @java.lang.Override
    public MMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moomoo.moonect.proto.MMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

