// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mMessages.proto

package com.moomoo.moonect.proto;

public interface MMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.MHeader mHeader = 1;</code>
   * @return Whether the mHeader field is set.
   */
  boolean hasMHeader();
  /**
   * <code>.MHeader mHeader = 1;</code>
   * @return The mHeader.
   */
  com.moomoo.moonect.proto.MHeader getMHeader();
  /**
   * <code>.MHeader mHeader = 1;</code>
   */
  com.moomoo.moonect.proto.MHeaderOrBuilder getMHeaderOrBuilder();

  /**
   * <pre>
   * Requests
   * </pre>
   *
   * <code>.MConnectReq mConnectReq = 2;</code>
   * @return Whether the mConnectReq field is set.
   */
  boolean hasMConnectReq();
  /**
   * <pre>
   * Requests
   * </pre>
   *
   * <code>.MConnectReq mConnectReq = 2;</code>
   * @return The mConnectReq.
   */
  com.moomoo.moonect.proto.MConnectReq getMConnectReq();
  /**
   * <pre>
   * Requests
   * </pre>
   *
   * <code>.MConnectReq mConnectReq = 2;</code>
   */
  com.moomoo.moonect.proto.MConnectReqOrBuilder getMConnectReqOrBuilder();

  /**
   * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
   * @return Whether the mHeartBeatReq field is set.
   */
  boolean hasMHeartBeatReq();
  /**
   * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
   * @return The mHeartBeatReq.
   */
  com.moomoo.moonect.proto.MHeartBeatReq getMHeartBeatReq();
  /**
   * <code>.MHeartBeatReq mHeartBeatReq = 3;</code>
   */
  com.moomoo.moonect.proto.MHeartBeatReqOrBuilder getMHeartBeatReqOrBuilder();

  /**
   * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
   * @return Whether the mSessionCreateReq field is set.
   */
  boolean hasMSessionCreateReq();
  /**
   * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
   * @return The mSessionCreateReq.
   */
  com.moomoo.moonect.proto.MSessionCreateReq getMSessionCreateReq();
  /**
   * <code>.MSessionCreateReq mSessionCreateReq = 4;</code>
   */
  com.moomoo.moonect.proto.MSessionCreateReqOrBuilder getMSessionCreateReqOrBuilder();

  /**
   * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
   * @return Whether the mSessionDeleteReq field is set.
   */
  boolean hasMSessionDeleteReq();
  /**
   * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
   * @return The mSessionDeleteReq.
   */
  com.moomoo.moonect.proto.MSessionDeleteReq getMSessionDeleteReq();
  /**
   * <code>.MSessionDeleteReq mSessionDeleteReq = 5;</code>
   */
  com.moomoo.moonect.proto.MSessionDeleteReqOrBuilder getMSessionDeleteReqOrBuilder();

  /**
   * <pre>
   * Notices
   * </pre>
   *
   * <code>.MStatusNotify mStatusNotify = 10;</code>
   * @return Whether the mStatusNotify field is set.
   */
  boolean hasMStatusNotify();
  /**
   * <pre>
   * Notices
   * </pre>
   *
   * <code>.MStatusNotify mStatusNotify = 10;</code>
   * @return The mStatusNotify.
   */
  com.moomoo.moonect.proto.MStatusNotify getMStatusNotify();
  /**
   * <pre>
   * Notices
   * </pre>
   *
   * <code>.MStatusNotify mStatusNotify = 10;</code>
   */
  com.moomoo.moonect.proto.MStatusNotifyOrBuilder getMStatusNotifyOrBuilder();

  /**
   * <pre>
   * Responses
   * </pre>
   *
   * <code>.MConnectRes mConnectRes = 12;</code>
   * @return Whether the mConnectRes field is set.
   */
  boolean hasMConnectRes();
  /**
   * <pre>
   * Responses
   * </pre>
   *
   * <code>.MConnectRes mConnectRes = 12;</code>
   * @return The mConnectRes.
   */
  com.moomoo.moonect.proto.MConnectRes getMConnectRes();
  /**
   * <pre>
   * Responses
   * </pre>
   *
   * <code>.MConnectRes mConnectRes = 12;</code>
   */
  com.moomoo.moonect.proto.MConnectResOrBuilder getMConnectResOrBuilder();

  /**
   * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
   * @return Whether the mHeartBeatRes field is set.
   */
  boolean hasMHeartBeatRes();
  /**
   * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
   * @return The mHeartBeatRes.
   */
  com.moomoo.moonect.proto.MHeartBeatRes getMHeartBeatRes();
  /**
   * <code>.MHeartBeatRes mHeartBeatRes = 13;</code>
   */
  com.moomoo.moonect.proto.MHeartBeatResOrBuilder getMHeartBeatResOrBuilder();

  /**
   * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
   * @return Whether the mSessionCreateRes field is set.
   */
  boolean hasMSessionCreateRes();
  /**
   * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
   * @return The mSessionCreateRes.
   */
  com.moomoo.moonect.proto.MSessionCreateRes getMSessionCreateRes();
  /**
   * <code>.MSessionCreateRes mSessionCreateRes = 14;</code>
   */
  com.moomoo.moonect.proto.MSessionCreateResOrBuilder getMSessionCreateResOrBuilder();

  /**
   * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
   * @return Whether the mSessionDeleteRes field is set.
   */
  boolean hasMSessionDeleteRes();
  /**
   * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
   * @return The mSessionDeleteRes.
   */
  com.moomoo.moonect.proto.MSessionDeleteRes getMSessionDeleteRes();
  /**
   * <code>.MSessionDeleteRes mSessionDeleteRes = 15;</code>
   */
  com.moomoo.moonect.proto.MSessionDeleteResOrBuilder getMSessionDeleteResOrBuilder();

  public com.moomoo.moonect.proto.MMessage.BodyCase getBodyCase();
}
