// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mBodies.proto

package com.moomoo.moonect.proto;

public interface MSessionDeleteReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MSessionDeleteReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sessionId = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <code>string sessionId = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();
}
